name: Continous Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # master branch로 변경합니다.
      - name: Checkout master
        uses: actions/checkout@master

      # node_modules를 매번 설치하면 비효율적이므로 캐시로 저장해둡니다.
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      # npm 패키지들을 설치합니다.
      - name: Install dependencies
        run: npm install

      # Docker Image를 자동으로 build하고 push합니다.
      # Docker Hub ID와 PW는 GitHub settings에 있는 secrets에 저장해둡니다.
      # [Your DockerHub ID]/[Your Repository Name] 예시) dal96k/woomin-facebook
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Docker image build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: dnfla960/idu-market-server
          tags: latest
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # Docker Hub에 새로운 Image가 push 완료되면 CodeDeploy Agent가 동작되도록 합니다.
      # --application-name과 --deployment-group-name은 아까 작성하신 애플리케이션 이름과 그룹 이름으로 대체하시면 됩니다.
      # [Your GitHub Repository] 예시) Woomin-Jeon/facebook-clone-server
      # "commitId=${GITHUB_SHA}" 코드가 자동으로 최신 commit을 불러옵니다.
      # 아까 보관해두었던 AWS_ACCESS_KEY_ID와 AWS_SECRET_ACCESS_KEY는 GitHub secrets에 저장해둡니다.
      - name: Trigger the CodeDeploy in EC2 instance
        run: aws deploy --region ap-northeast-2 create-deployment --application-name wooahan-agile --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name wooahan-agile-group --github-location repository=wooahan-agile/idu-market-server,commitId=${GITHUB_SHA}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          Default_region_name: ap-northeast-2